name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # Allow writing to the repository
      pull-requests: write  # Allow merging pull requests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for Mergeability
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const pullRequest = context.payload.pull_request;

            // Check if the pull request is mergeable
            if (pullRequest.mergeable === true) {
              console.log(`Merging PR #${pullRequest.number}`);
              await github.pulls.merge({
                owner,
                repo,
                pull_number: pullRequest.number,
              });
            } else {
              console.log(`PR #${pullRequest.number} is not mergeable.`);
            }
